import type { Options } from "json-schema-to-typescript";

/** Preferred config options for `json-schema-to-typescript`. */
export const schemaToTsConfig: Partial<Options> = {
  // prevent `[k: string]: unknown` from being added everywhere
  additionalProperties: false,
  bannerComment: [
    "/**",
    " * This file is autogenerated from the corresponding API definitions.",
    " * Do not edit this file directly.",
    " */",
    "",
    "import type { K8sResourceCommon, RequiredK8sResourceCommon } from '../K8sResourceCommon';",
  ].join("\n"),
  ignoreMinAndMaxItems: true,
  // prettier is done last in generate script
  format: false,
};
