import { writeFileSync } from "fs";
import { resolve } from "path";
import { generateOpenShiftTypesFromAPI } from "./generate-openshift-crd-types";
import { generateKubernetesTypesFromSwagger } from "./generate-k8s-resource-types";

const generateIndexFile = () => {
  writeFileSync(
    resolve(__dirname, "../generated/types/index.d.ts"),
    `// This file is autogenerated from the corresponding resources.
// Do not edit this file directly.

export * from './K8sResourceCommon';
export * from './kubernetes';
export * from './openshift';

`,
  );
};

generateOpenShiftTypesFromAPI();
generateKubernetesTypesFromSwagger();
generateIndexFile();
